# Generated by Django 3.1.7 on 2021-11-11 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('data', models.CharField(max_length=11)),
                ('place', models.CharField(max_length=200)),
            ],
        ),
    ]
