# Generated by Django 3.1.7 on 2021-12-20 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='data',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='event',
            name='place',
            field=models.CharField(max_length=500),
        ),
    ]
