# Generated by Django 3.1.7 on 2021-12-20 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='data',
            field=models.DateField(),
        ),
    ]
