# Generated by Django 3.1.7 on 2021-12-21 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_remove_event_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='likes',
        ),
    ]
